sudo: required
services:
  - docker

script:
  - docker build -t patrickhub/react-app-example3 .
  - docker images patrickhub/react-app-example3

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  provider: script
  script: docker push patrickhub/react-app-example3
  on:
    branch: master